---
- name: Install epel, yum utils and remi repo for php
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - yum-utils
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Install PHP 7.2 and httpd
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - httpd
#    - mod_ssl
    - php72
    - php72-php-fpm
    - php72-php-mysqlnd
    - php72-php-opcache
    - php72-php-xml
    - php72-php-xmlrpc
    - php72-php-gd
    - php72-php-mbstring
    - php72-php-json
  when:
    - php_version == 72
  notify:
    - restart php-fpm

- name: change owner of /var/lib/php
  file:
    path: /var/lib/php
    owner: root
    group: nginx
  notify:
    - restart php-fpm
