---
- name: Deploying /etc/nginx/nginx.conf
  template:
    src: ./templates/nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: '0644'
  tags: 
    - deployer_init

- name: Deploying /etc/nginx/conf.d/default.conf
  template:
    src: ./templates/default.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root
    mode: '0644'
  tags: 
    - deployer_init

- name: Deploying /etc/php-fpm.d/www.conf
  template:
    src: ./templates/www.conf.j2
    dest: "/etc/php-fpm.d/www.conf"
    owner: root
    group: root
    mode: '0644'
  tags: 
    - deployer_init